spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_mybatis?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.cmblog.blog.po
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    root: info
    com.cmblog.blog: debug
  file: log/bolg-dev.log
